CONFIG_ZMK_KEYBOARD_NAME="KeyballBLE"

# 右手とスタックサイズを同期
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=4096
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=4096
CONFIG_INPUT_THREAD_STACK_SIZE=4096

# 通信負荷を抑える
CONFIG_BT_CTLR_TX_PWR_0=y
CONFIG_ZMK_BLE_THREAD_PRIORITY=3
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# 基本機能
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_BATTERY_REPORTING=y

# LED関連オフ
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n
