CONFIG_ZMK_KEYBOARD_NAME="roba"

# 右手との通信を安定させるために出力を上げる
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 基本機能
CONFIG_ZMK_MOUSE=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y

# バッテリー報告
CONFIG_ZMK_BATTERY_REPORTING=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
